version: '3.8'
services:
  kotlin-spring:
    image: mysql:8.0
    platform: linux/amd64
    container_name: kotlin-spring-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=crud
      - MYSQL_USER=hongs
      - MYSQL_PASSWORD=local1234
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci